### ISSUE TITLE
Newly created vagrant machine results in 500 and also internal server error

### ISSUE THREAD

**Issue by therealmarv** [PyBossa/pybossa#1002]
First a 500 and then Internal server error

```
Error on request:
Traceback (most recent call last):
  File "/home/vagrant/pybossa-env/lib/python2.7/site-packages/werkzeug/serving.py", line 177, in run_wsgi
    execute(self.server.app)
  File "/home/vagrant/pybossa-env/lib/python2.7/site-packages/werkzeug/serving.py", line 165, in execute
    application_iter = app(environ, start_response)
  File "/home/vagrant/pybossa-env/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vagrant/pybossa-env/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/vagrant/pybossa-env/lib/python2.7/site-packages/flask/app.py", line 1410, in handle_exception
    return handler(e)
  File "/vagrant/pybossa/core.py", line 313, in _server_error
    return render_template('500.html'), 500
  File "/home/vagrant/pybossa-env/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/lib/python2.7/dist-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/vagrant/pybossa-env/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: 500.html
```

**Comment by therealmarv** [comment]
my own fault. Forgot `--recursive` during cloning *doh*
