### ISSUE TITLE
MemoryError when generating CSV ZIP file in the background

### ISSUE THREAD

**Issue by alejandrodob** [PyBossa/pybossa#1019]
See error:

Traceback (most recent call last):
  File "/home/pybossa/pybossa/env/local/lib/python2.7/site-packages/rq/worker.py", line 479, in perform_job
    rv = job.perform()
  File "/home/pybossa/pybossa/env/local/lib/python2.7/site-packages/rq/job.py", line 466, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/home/pybossa/pybossa/pybossa/jobs.py", line 126, in project_export
    csv_exporter.pregenerate_zip_files(app)
  File "/home/pybossa/pybossa/pybossa/exporter/csv_export.py", line 159, in pregenerate_zip_files
    self._make_zip(app, "task_run")
  File "/home/pybossa/pybossa/pybossa/exporter/csv_export.py", line 137, in _make_zip
    for line in csv_task_generator:
  File "/home/pybossa/pybossa/pybossa/exporter/csv_export.py", line 81, in _get_csv
    yield out.getvalue()
  File "/usr/lib/python2.7/StringIO.py", line 271, in getvalue
    self.buf += ''.join(self.buflist)
MemoryError

**Comment by therealmarv** [comment]
fixed
