### ISSUE TITLE
Facebook sign up not working

### ISSUE THREAD

**Issue by alejandrodob** [PyBossa/pybossa#1049]
Sign up with Facebook account does not work, resulting in an error page.

From New Relic logs:
Traceback (most recent call last):
File "/home/pybossa/pybossa/env/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request rv = self.dispatch_request()
File "/home/pybossa/pybossa/env/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args)
File "/home/pybossa/pybossa/env/local/lib/python2.7/site-packages/newrelic-2.40.0.34/newrelic/hooks/framework_flask.py", line 40, in _nr_wrapper_handler_ return wrapped(*args, **kwargs)
File "/home/pybossa/pybossa/env/local/lib/python2.7/site-packages/flask_oauthlib/client.py", line 691, in decorated return f(*((data,) + args), **kwargs)
File "./pybossa/view/facebook.py", line 66, in oauth_authorized user = manage_user(access_token, user_data, next_url)
File "./pybossa/view/facebook.py", line 77, in manage_user user = user_repo.get_by_name(user_data['username'])
KeyError: 'username'

**Comment by alejandrodob** [comment]
Seems that "username" was deprecated after GrapApi v1.0 (http://stackoverflow.com/questions/23428498/get-username-field-in-facebook-graph-api-2-0) so we need to update it to use any of the valid fields given by v2.0 (https://developers.facebook.com/docs/graph-api/reference/v2.0/user)
