### ISSUE TITLE
Exception when attempting to "edit the project details"

### ISSUE THREAD

**Issue by gbrauen** [PyBossa/pybossa#1204]
Just updated PyBossa from Master branch.  Originally installed in August 2015.

Now when I try to "edit the project details" for any project or when the project details are to be displayed as part of creating a new project, I see a message that:

    Ooops, Something's wrong
    It looks as though we have broken something on our system, sorry
    We will try to fix it as soon as we can!

In my admin email, I receive the following report:

    Exception on /project/test/update [GET]
    Traceback (most recent call last):
      File "/home/pybossa/pybossa/python_env/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
        response = self.full_dispatch_request()
      File "/home/pybossa/pybossa/python_env/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "/home/pybossa/pybossa/python_env/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "/home/pybossa/pybossa/python_env/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
        rv = self.dispatch_request()
      File "/home/pybossa/pybossa/python_env/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "/home/pybossa/pybossa/python_env/src/flask-login/flask_login.py", line 775, in decorated_view
        return func(*args, **kwargs)
      File "./pybossa/view/projects.py", line 458, in update
        title=title)
      File "/home/pybossa/pybossa/python_env/local/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
        context, ctx.app)
      File "/home/pybossa/pybossa/python_env/local/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
        rv = template.render(context)
      File "/home/pybossa/pybossa/python_env/local/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
        return self.environment.handle_exception(exc_info, True)
      File "/home/pybossa/pybossa/python_env/local/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "/home/pybossa/pybossa/pybossa/themes/default/templates/projects/update.html", line 3, in top-level template code
        {% import "projects/_helpers.html" as helper %}
      File "/home/pybossa/pybossa/pybossa/themes/default/templates/base.html", line 52, in top-level template code
        {% block content %}{% endblock %}
      File "/home/pybossa/pybossa/pybossa/themes/default/templates/projects/update.html", line 45, in block "content"
        {{ render_field(form.hidden, tooltip=_('Do you want to hide your project?')) }}
      File "/home/pybossa/pybossa/pybossa/themes/default/templates/_formhelpers.html", line 2, in template
        <div class="control-group {% if field.errors %} error {% endif %}">
      File "/home/pybossa/pybossa/python_env/local/lib/python2.7/site-packages/jinja2/environment.py", line 408, in getattr
        return getattr(obj, attribute)
    UndefinedError: 'pybossa.forms.forms.ProjectUpdateForm object' has no attribute 'hidden'

**Comment by teleyinex** [comment]
Hi @gbrauen,

It looks like you only updated the source code. When you update the PyBossa code, you have always to run the following command to upgrade/migrate the database too:

```bash
alembic upgrade head
```

**NOTE**: take a backup of your db just in case.

We've that information in the documentation [here](http://docs.pybossa.com/en/latest/install.html#updating-pybossa). As well as in our [README](https://github.com/PyBossa/pybossa#installing-and-upgrading). Please, try that command (remember to have the virtualenv active if you are using one). 

All the best,

Daniel

**Comment by alejandrodob** [comment]
Hi, 

Have you tried to also upgrade the latest changes of the theme submodule? This one is for the templates, that are stored in a separate Git repository. Sometime, whenever we make some changes to the backend, these need to have a reflection in the templates too, and that seems to be the case here.

If the previous thing does not work, you can try that and it should fix it.

In order to update the theme, please go to the folder pybossa/pybossa/themes/default and run

```git pull```

**Comment by gbrauen** [comment]
@teleyinex I had previously issued the command

    alembic upgrade head

as part of following the instructions [here](http://docs.pybossa.com/en/latest/install.html#update-pybossa-core-and-migrating-the-database-table-structure).

@alejandrodob Issuing the command 

    git pull origin master

in the pybossa/pybossa/themes/default folder has now fixed my issue.

Thank you for the quick replies.

Best wishes,
Glenn

**Comment by teleyinex** [comment]
Our pleasure @gbrauen
