### ISSUE TITLE
Export fails "IOError: [Errno 2] No such file or directory:"

### ISSUE THREAD

**Issue by jacksongs** [PyBossa/pybossa#1311]
Hello,

Testing a new site based on Pybossa on Digital Ocean. Great work, looking forward to seeing what kind of traction it gets.

I've been testing the CSV Export functionality but can't get it to work.

I've activated logging and this is the traceback when I push the export button (it's a 500 server error):

`pybossa.core:ERROR:[2016-09-19 05:56:30,756] Exception on /project/senate44test/tasks/export [GET] [in /home/pybossa/pybossa/env/local/lib/python2.7/site-packages/flask/app.py:1423]
Traceback (most recent call last):
  File "/home/pybossa/pybossa/env/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pybossa/pybossa/env/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pybossa/pybossa/env/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pybossa/pybossa/env/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pybossa/pybossa/env/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./pybossa/view/projects.py", line 1116, in export_to
    return {"json": respond_json, "csv": respond_csv, 'ckan': respond_ckan}[fmt](ty)
  File "./pybossa/view/projects.py", line 1023, in respond_csv
    res = csv_exporter.response_zip(project, ty)
  File "./pybossa/exporter/__init__.py", line 106, in response_zip
    return self.get_zip(project, ty)
  File "./pybossa/exporter/__init__.py", line 95, in get_zip
    attachment_filename=filename)
  File "/home/pybossa/pybossa/env/local/lib/python2.7/site-packages/flask/helpers.py", line 520, in send_file
    file = open(filename, 'rb')
IOError: [Errno 2] No such file or directory: '/home/pybossa/pybossa/uploads/user_1/13_senate44test_task_csv.zip'`

I have the default upload settings in the settings_local.py file.

`## If you want to use the local uploader configure which folder
UPLOAD_METHOD = 'local'
UPLOAD_FOLDER = 'uploads'`

Meanwhile, the API endpoints work fine, so I can get the results I need in json. But a colleague really needs a csv export to see the results in Excel.

Any suggestions?

**Comment by teleyinex** [comment]
Hi,

As you cloned the repository, the uploads folder is not created. Check the error: No such file or directory. Can you double check if you have an uploads folder in your pybossa installation? If not, create it by hand, give it permissions, and restart pybossa. That should do the trick ;-)

Cheers

**Comment by jacksongs** [comment]
Thanks for the prompt reply.

The uploads folder exists, but not the uploads/user_1 folder. I will create an uploads/user_1 folder, chmod the s*** out of it and see where I get to.

---------

UPDATE
====

That worked. Legend, thanks a bunch.

**Comment by teleyinex** [comment]
If that folder exists, then, the user_1 should be automagically created by PYBOSSA. If this is not happening, then we've a bug, or your uploads folder does not have the right permissions. Can you debug that?

**Comment by jacksongs** [comment]
uploads folder only had write access for root user. The uwsgi server is being run by a pybossa (non-root) user under supervisor.

Let me know if you need any more information.
